// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebServer.Api.Entities;

#nullable disable

namespace WebServer.Api.Migrations
{
    [DbContext(typeof(HaxballDbContext))]
    [Migration("20240512184804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebServer.Api.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Elo1v1")
                        .HasColumnType("integer");

                    b.Property<int>("Elo4v4")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesCount1v1")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesCount4v4")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("WinMatchesCount1v1")
                        .HasColumnType("integer");

                    b.Property<int>("WinMatchesCount4v4")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
